### ISSUE TITLE
Add a check user command

### ISSUE THREAD

**Issue by jdd-software** [SOBotics/Guttenberg#106]
Add a check user command

     checkuser <userId>

That can only be run by RO and moderators `user.isModerator() || user.isRoomOwner()`

1. Get all posts of user (see Detecto Plagio code base)
2. Develop algorithm to find what to search on (es. Second complete sentence, comments in code etc). For this we need testing to find best search strategy
3. Call google or bing api to find posts (included only SO?), we can't compare if off-site, but we could notify.
4. Run Guttenberg algo on result (first 3? SO results)
5. Notify in chat the result (watch out for rate limit, hence throttle reports)

**Comment by Bhargav-Rao** [comment]
The code of Detecto Plagio is quite simple, the main algo running here is:

```
        int userId;
        String url = "http://api.stackexchange.com/2.2/users/"+userId+"/answers";

        JsonObject json =  JsonUtils.get(url,
                "sort","activity",
                "site","stackoverflow",
                "pagesize","100",
                "page","1",
                "order","desc",
                "key",apiKey);

        if (json.has("items")){
            for (JsonElement element: json.get("items").getAsJsonArray()){
                JsonObject object = element.getAsJsonObject();
                try {
                    Thread.sleep(3000); // Waiting to prevent chat rate limit
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
                room.send("@gut check "+object.get("answer_id").getAsString());
            }
        }
```
