### ISSUE TITLE
Allow feedback

### ISSUE THREAD

**Issue by FelixSFD** [SOBotics/Guttenberg#13]
* tp: If the post is plagiarism
* fp: If both posts don't have anything to do with each other

---

This will need a web-dashboard like Sentinel

**Comment by ArtOfCode-** [comment]
Having a web dashboard also needs someone to host it. That needs a Linux server - if you've got one, great. If not, might be worth talking to Undo to see if he still has any spare space.

**Comment by FelixSFD** [comment]
At the moment, I have a Raspberry Pi. Guttenberg is running on it, too. But I'm planning to rent a V-Server which I want to use for other stuff as well

**Comment by ArtOfCode-** [comment]
Pi probably isn't enough to handle a Rails server, I think

**Comment by FelixSFD** [comment]
I thought of using Swift or PHP. Swift won't be that easy, but I've always wanted to try to make a server application in Swift since IBM introduced [Kitura](https://github.com/IBM-Swift/Kitura) at [WWDC 2016](https://developer.apple.com/videos/play/wwdc2016/415/).

**Comment by ArtOfCode-** [comment]
![PHP](https://blog.codinghorror.com/content/images/uploads/2012/06/6a0120a85dcdae970b017742d249d5970d-800wi.jpg)

> I can’t even say what’s wrong with PHP, because – okay. Imagine you have uh, a toolbox. A set of tools. Looks okay, standard stuff in there.

> You pull out a screwdriver, and you see it’s one of those weird tri-headed things. Okay, well, that’s not very useful to you, but you guess it comes in handy sometimes.

> You pull out the hammer, but to your dismay, it has the claw part on both sides. Still serviceable though, I mean, you can hit nails with the middle of the head holding it sideways.

> You pull out the pliers, but they don’t have those serrated surfaces; it’s flat and smooth. That’s less useful, but it still turns bolts well enough, so whatever.

> And on you go. Everything in the box is kind of weird and quirky, but maybe not enough to make it completely worthless. And there’s no clear problem with the set as a whole; it still has all the tools.

> Now imagine you meet millions of carpenters using this toolbox who tell you “well hey what’s the problem with these tools? They’re all I’ve ever used and they work fine!” And the carpenters show you the houses they’ve built, where every room is a pentagon and the roof is upside-down. And you knock on the front door and it just collapses inwards and they all yell at you for breaking their door.

> That’s what’s wrong with PHP.

**Comment by ArtOfCode-** [comment]
Maybe I'm biased towards Rails, but I do think it's a good choice for something that just needs basic functionality (but has the ability to do complex stuff too), and won't make your server a walking vulnerability.

**Comment by FelixSFD** [comment]
I'm not gonna learn Ruby for this ;-) Anyway, I have no time for this at the moment. Maybe in a few weeks

**Comment by ArtOfCode-** [comment]
Shouldn't be too difficult to take a copy of Sentinel and modify it for this, though. I might get time to do that at some point, if you wanted.
