### ISSUE TITLE
Add possibility to blacklist users from interacting with the bot

### ISSUE THREAD

**Issue by FelixSFD** [SOBotics/Guttenberg#131]
Since we are no restricting feedback to ROs and mods anymore (#129 ), we should be able to blacklist users.

**Comment by ArtOfCode-** [comment]
Either that, or you only allow privileged users to feed back (a la Smokey). Instead of blacklisting, you whitelist, and can revoke privileges if they're abused. Either works.

**Comment by FelixSFD** [comment]
We didn't have many problems with users sending feedback to Natty, so I don't think we'll have a problem here. I think I'll just copy Natty's code to blacklist users.

**Comment by Bhargav-Rao** [comment]
No, don't go to copy Natty's code to auto-blacklist users. It's a bit of a mess at the moment and I've not got time to clean it up. It might end up blacklisting random users. 

You can have a manual blacklist (just like how there's a manual whitelist for Smokey). Add the blacklisted users either through a chat-command or by adding it in the list, but let it be manual.  Having three attributes, "userid", "chat host", "room", would be enough, I guess.
