### ISSUE TITLE
How should we provide feedback to Guttenberg? 

### ISSUE THREAD

**Issue by Bhargav-Rao** [SOBotics/Guttenberg#136]
Now that feature https://github.com/SOBotics/Guttenberg/issues/13 has been implemented, we can provide feedback to Guttenberg.

Can we come up with a clear agreement about how we need to feedback and the etiquette that is to be followed post feedback? Once we come to a conclusion, we should add the final decisions on a webpage. 

I'm specifically looking for what to do when: 

1. Guttenberg reports a plagiarism, and it is a correct find.
2. Guttenberg reports a plagiarism, and it is not plagiarized. 
3. Guttenberg reports a plagiarism, but it is attributed to the original post. 
4. Guttenberg reports a repost, and CopyPastor clearly shows that they are perfect reposts. (i.e. automatic moderator flag)
5. Guttenberg reports a repost, but CopyPastor shows that there are just formatting differences between the two versions.  
6. Guttenberg reports a repost, and CopyPastor shows that there are quite a few differences between the two versions.

**Comment by jdd-software** [comment]
tp=1 and 4,5 fp=2,6 and case 3 baah?? either fp or ta if we like to separate them.

**Comment by Bhargav-Rao** [comment]
Yeah, agree with that, @jdd-software. For 3, I feel that we can reply with tp, comment asking to dupe instead of copying, but no flag. 

And about flagging, I'd say we flag in cases 1 and 4; comment  but no flag in 3 and 4.

**Comment by pbdevch** [comment]
An those comments you mentioned @Bhargav-Rao also should be added to the auto comments page on https://sobotics.org/auto-comments/. Maybe we should create a PR for that once the comments are defined.

**Comment by Jinx88909** [comment]
I'd agree with @jdd-software here. In case of three I feel a tp would be the right feedback. I think it would be also good to include in docs a "when" and "how" to flag for the tps.

**Comment by FelixSFD** [comment]
| Case | Feedback | Flag? | Comment? |
| --- | --- | --- | --- |
| Guttenberg reports a plagiarism, and it is a correct find. | tp | x | o |
| Guttenberg reports a plagiarism, and it is not plagiarized. | fp | o | o |
| Guttenberg reports a plagiarism, but it is attributed to the original post. | tp | o | o |
| Guttenberg reports a repost, and CopyPastor clearly shows that they are perfect reposts. (i.e. automatic moderator flag) | tp | o | x |
| Guttenberg reports a repost, but CopyPastor shows that there are just formatting differences between the two versions. | tp | x | x |
| Guttenberg reports a repost, and CopyPastor shows that there are quite a few differences between the two versions. | fp | o | o |


----

@Bhargav-Rao Would it be useful for the mods, if we had a standard flag-text?

Something like this?

Plag: 
> This post is plagiarized from an other answer. [link to CopyPastor] #plagiarism

Repost (when it's not autoflagged after several reposts and a comment): 
> The user is posting the same answer to lots of questions instead of flagging them as duplicate. Example: [link to CopyPastor]

**Comment by FelixSFD** [comment]
I've created a file with guidelines and texts. Feel free to edit it.

https://github.com/SOBotics/Guttenberg/blob/136-feedback-guidelines/feedback.md

**Comment by Bhargav-Rao** [comment]
Yes, having a CP link would be quite beneficial [as Martijn mentions here](https://chat.stackoverflow.com/transcript/message/40823948#40823948). However, let us only link the CP report whenever it is clear on CP that it is plagiarized. Like [this one](http://copypastor.sobotics.org/posts/14). 

For the reposts, the comment can be:

`Please don't add the [same answer to multiple questions](http://meta.stackexchange.com/questions/104227/is-it-acceptable-to-add-a-duplicate-answer-to-several-questions). Answer the best one and flag the rest as duplicates, once you earn enough reputation. If it is not a duplicate, [edit] the answer and tailor the post to the question.`

**Comment by Bhargav-Rao** [comment]
Also, the flag text should contain a link to the other answer. 

> This post is plagiarized from an other answer [link to the other answer], as can be seen here [link to CopyPastor] #plagiarism

and for reposts

> The answer is a repost of their other answer [link to the other answer], but as there are slight differences as seen here [link to CopyPastor], an auto flag would be raised.

**Comment by FelixSFD** [comment]
I guess you mean "**no** auto flag would be raised", since we are only flagging, if it wasn't autoflagged yet?

**Comment by Bhargav-Rao** [comment]
Ah, yes, my bad. I edited the post. I wanted to mention "an auto flag wouldn't be raised."
