### ISSUE TITLE
Guttenberg not reporting reposts

### ISSUE THREAD

**Issue by Bhargav-Rao** [SOBotics/Guttenberg#143]
Ever since version 0.10.0 was released, the number of repost reports has drastically decreased. See

https://chat.stackoverflow.com/search?user=7418352&q=repost

**Comment by FelixSFD** [comment]
This might have something to do with #130 
https://github.com/SOBotics/Guttenberg/commit/7801e39c6b884d3b84483f296acd89669c268392
