### ISSUE TITLE
Resource-leak when reading guttenberg.properties

### ISSUE THREAD

**Issue by FelixSFD** [SOBotics/Guttenberg#31]
https://github.com/SOBotics/Guttenberg/pull/25#discussion_r98058594

Might be somewhere else as well

**Comment by Tunaki** [comment]
Perhaps. You can grep for `InputStream` to fix all the usage :) (and `OutputStream`).

**Comment by FelixSFD** [comment]
I don't understand the difference between my code and the try() {} catch {} you proposed in the comment
