### ISSUE TITLE
Replace the use of printStackTrace() with a logger

### ISSUE THREAD

**Issue by Tunaki** [SOBotics/Guttenberg#32]
Instead of using `printStackTrace()` to log exceptions, it would be preferable to use the standard mechanism of loggers.

Since Chatexchange already brings slf4j-api on the classpath (which is a facade for every other logging library in Java), you could add a dependency on slf4j-log4j12 in the POM. Then start using the logging features like:

```java
private static final Logger LOGGER = LoggerFactory.getLogger(MyClass.class);

try {
  LOGGER.info("Doing the miraculous thing with parameters {} and {}", param1, param2);
} catch (SomeException e) {
  LOGGER.error("Ups", e); // log the error with proper stacktrace
}
```

**Comment by FelixSFD** [comment]
Where do I find the logs generated by the logger? I can't see them in eclipse

**Comment by Tunaki** [comment]
Yeah you would need a log4j configuration file to be present, for example on the classpath.

To start, you could create the file `src/main/resources/log4j.properties` with

```
log4j.rootCategory=INFO, stdout

log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=%5p [%c{1}:%L] %d{ISO8601} - %m%n
```

which would log every INFO or more logs to the console.

**Comment by Tunaki** [comment]
Yup, there is the built-in `DailyRollingFileAppender` class.
