### ISSUE TITLE
Status command

### ISSUE THREAD

**Issue by FelixSFD** [SOBotics/Guttenberg#7]
Should return 
- Guttenberg's version
- the number of checked and caught posts
- running since xxxxxxx

**Comment by FelixSFD** [comment]
@Tunaki Do you know how I can display Guttenberg's version number? It's defined in `pom.xml`

**Comment by Tunaki** [comment]
Yes, you can filter a resource that would contain `${project.version}`. Then the Java code would read that resource and print it. There are examples here https://maven.apache.org/plugins/maven-resources-plugin/examples/filter.html
