### ISSUE TITLE
Add standby-mode

### ISSUE THREAD

**Issue by FelixSFD** [SOBotics/Guttenberg#75]
Guttenberg should check on Redunda, if it should be on standby or running

**Comment by ArtOfCode-** [comment]
For future reference:

HTTP POST to `https://redunda.erwaysoftware.com/status.json` with a `key` parameter for the current bot instance. The returned JSON will contain a `should_standby` key, which indicates whether the instance that pinged should be in standby mode.

**Comment by FelixSFD** [comment]
Wait. Something is not working. Guttenberg is stuck in standby
