### ISSUE TITLE
false positive when comparing low length javascript / xml posts

### ISSUE THREAD

**Issue by jdd-software** [SOBotics/Guttenberg#91]
I have noticed that they often get indicated to [same post](http://chat.stackoverflow.com/search?q=https%3A%2F%2Fstackoverflow.com%2Fa%2F43390566%2F4687348&room=111347), hence if we could whitelist post, we could automatically remove all false positive related to it and drastically reduce the problem.

Example: `@gut whitelist https://stackoverflow.com/a/43390566/4687348`

The solution could also be to simple send `fp` to bot and it automatically whitelist the original post since it's probably very unlikely that someone will actually plag. that specific post and even if the reduction of fp may be more important then a single tp.

**Comment by Floern** [comment]
Not sure if this is a good idea. Gutty will just find another "canonical" if this one gets whitelisted. Also real plagiarism involving that post would be ignored.

IMHO it looks like there is a problem with the Stack Snippets template code, which seems also be considered as identical code.. Maybe that could be fixed.

**Comment by jdd-software** [comment]
@Floern  The logic is if it finds whitelisted post, it will not continue (post can not be checked), hence it does not search for others. I believe in general it's yes related to stack snippet, but also to length and type of code example Android xml.  Whitelist a post basically is a way to go around the problem, telling to the system that "This type of post (stack snippet, short lenght, android xml ecc) can't be checked so carry on.
